export const CUSTOMERS_GET = `http://localhost:8080/api/customers`;
export const EMPLOYEES_GET = `http://localhost:8080/api/employees`;
export const GROUPS_GET = `http://localhost:8080/api/groups`;
export const EMPLOYEE_POST = `http://localhost:8080/api/employees/register`;
export const ITEMS_GET = `http://localhost:8080/api/items`;
export const SUPPLIER = `http://localhost:8080/api/suppliers`;
export const ITEM_SUPPLIED = `http://localhost:8080/api/items/search/supplier`;
export const ITEM_ORDER = `http://localhost:8080/api/item/order`;
export const token = `eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzMW1wbGUiLCJleHAiOjE2Njc2Njc3ODd9.j3bkrVyq-MBNFbfGW8BE2gtbxKI8DwPcHSb3ZiyiRxBhv6KgYoTCgWq3XbOLbjZQ31y2sCmGoJ67KXvV9vJ10w`;
export const key = `3f7b638c409019f370014fe9a7a24cc5`;
export const API_UPLOAD = `https://api.imgbb.com/1/upload?key=${key}`;
export const AVATAR_API = (fullname) => `https://avatars.dicebear.com/api/initials/${fullname}.svg`;
